---
title: "About the Open Source Patent Analytics Project"
author: "Paul Oldham"
date: "3 March 2015"
output: slidy_presentation
---

## About the Project

1. This project provides practical guidance and resources in the use of open source and free tools for patent analysis. 
2. Patent information is a valuable source of technical data on trends in scientific research and development and is increasingly used to inform policy debates and decisions. 
3. Millions of patent records are available online through patent databases such as [EPO espacenet](http://worldwide.espacenet.com/?locale=en_EP), [Patent Scope](https://patentscope.wipo.int/search/en/search.jsf), [Google Patents](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CCIQFjAA&url=http%3A%2F%2Fwww.google.com%2Fpatents&ei=7LFIVeyiIInmau2rgMgL&usg=AFQjCNG_XlAI_9dSaH28NeN5O6bXJSSuSw&sig2=lgFU0x6MQCnaWZBXgPYDAA&bvm=bv.92291466,d.d2s) and [Patent Lens](http://www.lens.org/lens/) and [Free Patents Online](http://www.freepatentsonline.com) or [Google Bulk Download of USPTO patents](https://www.google.com/googlebooks/uspto.html)
3. The questions this project seeks to address are:
    + How to obtain patent data in a form that is useful for different types of analysis?
    + How to tidy, analyse, visualize and share patent data using open source or free software?
    + How to promote confidence that the results of analysis are transparent and robust for informed decision-making? 

## Topics

The project is divided into seven main topics but we will see how it develops:

1. Approaching Patent Data
2. Obtaining Patent Data
3. Tidying Patent Data
4. Analysing Patent Data
5. Visualising Patent Data
6. Sharing Patent Data
7. Tools and Resources

Each of these topics will be accompanied by documentation, videos, code and resources to assist with patent analysis. The project home page and repository is hosted on [Github](http://poldham.github.io/opensource-patent-analytics/) which includes links to the [Open Source Patent Analytics](https://www.youtube.com/channel/UCwFhEASbKdm6WYoax73XsOw) YouTube channel of video walkthroughs on software and common tasks. We have created a set of patent datasets that are accessible on the project's [Google Drive](https://drive.google.com/folderview?id=0B4piiKOCkRPDNThTWU1QQVYyRnM&usp=sharing) and on the Github repository.

We welcome your inputs to the project by contributing files, code or tips to the GitHub repository and will be developing the project wiki. Hopefully we can build a repository of useful open source tools that everyone can use. 

## Tools

We will mainly focus on: 

- Using free databases and APIs to retrieve patent data [Open Patent Services](http://www.epo.org/searching/free/ops.html).
- Using tools such as [Open Office Calc](https://www.openoffice.org) and [Google Refine/Open Refine](http://openrefine.org) for basic data cleaning.
- Using R in [RStudio](http://www.rstudio.com) for tidying, analysing and visualizing patent data.
- Using [Python](https://www.python.org) to retrieve patent data.
- Using [Google Charts](https://developers.google.com/chart/interactive/docs/gallery), [Tableau Public](https://public.tableau.com/s/gallery) and [Shiny Apps](http://shiny.rstudio.com/gallery/) to create interactive dashboards
- Using [Gephi](http://gephi.github.io) to visualize networks (inventors, applicants, IPCs)
- Using mapping tools such as [Google Maps](https://www.google.co.uk/maps/@54.0441627,-2.801143,13z) or [Open Street Map](http://www.openstreetmap.org/#map=18/54.04885/-2.79982) 

Please submit suggestions for other free tools that you think will be useful to me at the project email address [email](mailto: openpatentanalytics@gmail.com)

- Paul Oldham
- Updated 05/05/2015
-



